name: Flujo Personalizado

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout código
              uses: actions/checkout@v2

            - name: Ejecutar acción personalizada
              uses: ./.github/actions/personalizas/action.yml