name: Test

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

           # - name: Run tests
           #   run: npm test

            - name: Check test coverage
              run: |
                    coverage=$(npm run coverage -- --json | jq -r '.total.lines.pct')
                    if (( $(echo "$coverage > 80" | bc -l) )); then
                        echo "Test coverage is above 80%"
                    else
                        echo "Test coverage is below 80%"
                        exit 1
                    fi